### ISSUE TITLE
Wrong Publish Command

### ISSUE THREAD

**Issue by talha08** [teepluss/laravel-recaptcha#1]
Previous Command/ Wrong Command:
............................................................................
----> php artisan publish:config teepluss/recaptcha

Correction:
..............................................................................
----> php artisan config:publish teepluss/recaptcha

**Comment by masiur** [comment]
@teepluss 
**# Publish config using artisan CLI.** 
`php artisan publish:config teepluss/recaptcha`

the command is wrong

## Correction

`php artisan config:publish teepluss/recaptcha`

Thank you, @talha08

**Comment by talha08** [comment]
Your recaptcha  package is very simple and it's save my time many times , Thank you too for your package :)  @teepluss
